/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.97.0
*/

import { Contract, ContractFactory, decompressBytecode } from "fuels";
import type { Provider, Account, DeployContractOptions, DeployContractResult } from "fuels";

import { Aoc2024 } from "./Aoc2024";

const bytecode = decompressBytecode("H4sIAAAAAAAAA6VUTWgTQRR+iVsabwNNNUxbDZqUFRRTFOlxl03Y1G3pSAV7WTYXoQfBskoQvORYPLWCP8eIHhQ8TBYPHjzs0WNu9tiLYKELvRRSeqjf7GZNrLEgLiw77833vffNe2+W71foMVGW4kfrucdhhh0fKx/xPUFblA3dlf0su2OE3GiQX80KZmoG3yUq9m7Q6tFOVhztaMB/51aXhC2lF9E5YQWrfp1yuplv9Xn1v/C+9Xn74F0Ar5Xy1Nq1pXBrjFxHCn+RcmyhFHpRUQhHflW2vqDBZtw3iOlRicCR4DPd+tRyLRlrRVyh/MIJ2uAwxYHdFk7nR2rz3eJJXV9iXY78DP555CgISzK/CrxZMoQdNOI8NU3pbEB/24uMPHxnoW8SseeT2PkQ2Fy8rqk87GSegNvIsxwUfAHMUpn4buUk5gNf7tJELR9OoBZ8kahZpWnETXKMjvuxH7d+Sty33IkxeoIZG4V5pupwZSm/2VykLOr89JbxRw/f8Htd8g2NZrHHjXX0s8NQt0vKh+9lb49KqF8R9SnEvbU79Xgd16/zfuCX8wO/3E797oqccpflNHo6gx5orKYZk6hts04Z5B8DLju1dLM1i9roM1XiAhqcTsOLxFX/LvALZYOZVVJr3SwbyPkE/bruRZUKejuHvGJIz+ZAT7Ax8Acb0B0O6Vsb0t1L/dB4UdQYQ/41nP2aMIuq/2qmMXeyNTRD60MztI7YKkZsj+hnIbknwDmd7cFsyc1kBkoh/Hrqx72ZLZuMXhCdeZlL7jK32sTtHXJN2Ad4Dxm9xt4rYG73SGHHU+wWEUvxsaYImiz5i/tc7Q/44//Az/wn/7T8Q2cFr5p5xw9wXw7pt3Pa+Lc9eviged+b8+aSH1//0bo/AdixfsYQBQAA");

export class Aoc2024Factory extends ContractFactory {

  static readonly bytecode = bytecode;

  constructor(accountOrProvider: Account | Provider) {
    super(bytecode, Aoc2024.abi, accountOrProvider);
  }

  override deploy<TContract extends Contract = Contract>(
    deployOptions?: DeployContractOptions
  ): Promise<DeployContractResult<TContract>> {
    return super.deploy({
      storageSlots: Aoc2024.storageSlots,
      ...deployOptions,
    });
  }

  static async deploy (
    wallet: Account,
    options: DeployContractOptions = {}
  ): Promise<DeployContractResult<Aoc2024>> {
    const factory = new Aoc2024Factory(wallet);
    return factory.deploy(options);
  }
}
