[package]
name = "solution"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version.workspace = true

[dependencies]
stylus-sdk.workspace = true

[lib]
crate-type = ["lib", "cdylib"]

[features]
